name: Alpine Package Releaser
description: |
  Builds and releases to GitHub pages the Alpine Linux packages from the
  repository.
author: Ivan Valdes Castillo <github@ivan.vc>
branding:
  icon: 'archive'
  color: blue
secrets:
  - GITHUB_TOKEN
  - RSA_PUBLIC_KEY
  - RSA_PRIVATE_KEY
runs:
  using: docker
  image: Dockerfile
