name: Alpine Package Releaser
description: |
  Builds and releases to GitHub pages the Alpine Linux packages from the
  repository.
author: Ivan Valdes Castillo <github@ivan.vc>
branding:
  icon: 'archive'
  color: blue
inputs:
  author:
    description: |
      The author to use for the released packages (i.e., John Doe
      <john@example.com>)
    required: true
  rsa_public_key:
    desciption: The RSA public key used to sign the packages.
    required: true
  rsa_private_key:
    description: The RSA private key used to sign the packages.
    required: true
  commit_message:
    description: The commit message when updating the pages.
  generate_index_pages:
    description: Set to false if you don't want to generate index pages.
    default: 'true'
secrets:
  - GITHUB_TOKEN
runs:
  using: docker
  image: Dockerfile
