name: Alpine Package Releaser
description: |
  Builds and releases to GitHub pages the Alpine Linux packages from the
  repository.
author: Ivan Valdes Castillo <github@ivan.vc>
branding:
  icon: 'archive'
  color: blue
inputs:
  author:
    description: |
      The author to use for the released packages (i.e., John Doe
      <john@example.com>)
    required: true
  rsa_public_key:
    desciption: The RSA public key used to sign the packages.
    required: true
  rsa_private_key:
    description: The RSA private key used to sign the packages.
    required: true
  commit_message:
    description: The commit message when updating the pages.
  generate_index_pages:
    description: Generate index pages for each directory.
    default: 'false'
  generate_single_index_page:
    description: |
      Generate a single index page for the repository. If neither this nor
      generate_index_pages are selected, then it will not generate any index
      pages, this option takes precedence over generate_index_pages.
    default: 'true'
  index_page_template:
    description: |
      Override the default index page template. Point this to a file that exists
      in the gh-pages branch. Refer to this repo's index.html.tpl for the
      available template variables. Make sure to keep the
      "ABUILD_RELEASER_ACTION_INDEX_TEMPLATE" comment, to know it's an generated
      page.
secrets:
  - GITHUB_TOKEN
runs:
  using: docker
  image: Dockerfile
